version: '3'

services:

  php:
    build: './docker/php'
    volumes:
      - '.:/var/www/html'
    ports:
      - '9000:9000'

  worker:
    build: './docker/php'
    volumes:
      - '.:/var/www/html'
    entrypoint: ["php", "artisan", "queue:listen"]
    restart: unless-stopped

  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/volume:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  nginx:
    image: 'nginx:stable-alpine'
    ports:
      -  '80:80'
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  meilisearch:
    image: 'getmeili/meilisearch'
    user: 'root'
    ports:
      - '7700:7700'
    user: '1000:1000'
    volumes:
      - './docker/meilisearch/volume:/home/meili/data.ms'
    environment:
      - 'MEILI_MASTER_KEY=${MEILISEARCH_KEY}'


